language: cpp

sudo: false

script: make all && make test

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - cmake
    - g++-5
    - php5-cli
    - libboost1.55-dev

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX=g++-5; fi
