# Copyright (c) 2015, Yahoo Inc. All rights reserved.
# Copyrights licensed under the New BSD License.
# See the accompanying LICENSE file for terms.

---
- settings:
    language: en-US

  provider:
    host:
      - red

  color: red

- settings:
    language: en-US
    property: [search, frontpage]
    partner: [att, mozilla]

  color: orange

- settings:
    tier: layer7
    language: en-US

  color: cyan

  keys:
    - provider

- settings:
    language: en-US
    property: frontpage
    partner: verizon

  color: cyan

  keys:
    - color
    - host

- settings:
    language: en-US
    property: frontpage

  provider:
    host:
      - purple
      - cyan
    shouldRun: true

  color: purple

- settings:
    language: pt-BR
    property: search
    partner: att

  provider:
    host:
      - gray
    shouldRun: false
    timeout: 5000

  color: gray

- settings:
    language: pt-BR
    property: search

  provider:
    host:
      - blue

  color: blue

- settings:
    language: en-UK
    property: search
    partner: orange

  color: blue

  parameter:
    n:
      type: number
      array: false
    o:
      type: boolean
      array: true

- settings:
    property: frontpage

  provider:
    host:
      - yellow

  color: yellow

- settings:
    property: search

  provider:
    host:
      - green

  color: green

  parameter:
    n:
      type: number
      array: true
    o:
      type: boolean

- settings:
    property: search
    partner: verizon

  parameter:
    o:
      array: false

  myHash:
    foo: bar
