# Copyright (c) 2015, Yahoo Inc. All rights reserved.
# Copyrights licensed under the New BSD License.
# See the accompanying LICENSE file for terms.

---
- dimensions:
  - language
  - property
  - partner

- settings: master

  provider:
    host:
      - brown
    path: x
    port: 1
    shouldRun: true
    timeout: 10
    clas:
      name: brown
      address: x

  color: gray

  myArray:
    - hello
    - world

- settings:
    language: en-US

  provider:
    host:
      - red

  color: red

- settings:
    language: en-US
    property: frontpage
    partner: att

  color: orange

- settings:
    language: en-US
    property: frontpage
    partner: verizon

  color: cyan

- settings:
    language: en-US
    property: frontpage

  provider:
    host:
      - purple
      - cyan
    shouldRun: true

  color: purple

- settings:
    language: pt-BR
    property: search
    partner: att

  provider:
    host:
      - gray
    shouldRun: false
    timeout: 5000

  color: gray

- settings:
    language: pt-BR
    property: search

  provider:
    host:
      - blue

  color: blue

- settings:
    language: en-UK
    property: search
    partner: orange

  color: blue

- settings:
    property: frontpage

  provider:
    host:
      - yellow

  color: yellow

- settings:
    property: search

  provider:
    host:
      - green

  color: green
